# Hourly Average With Inconsistent Time Capture

In [17]:
import sys
sys.path.append("..") # Adds higher directory to python modules path.

In [18]:
from sqlalchemy import create_engine

In [19]:
# Load configuration
from config import DATABASE_URI

In [20]:
# Create a database connection
conn = create_engine(DATABASE_URI, echo=False)

In [21]:
# Query the database
query = "SELECT date, vehicles FROM data"
df = pd.read_sql(query, conn)
df['interval'] = df['date'].dt.strftime('%H%M') #.astype('int64')

In [22]:
grouped = df.groupby('interval') #, as_index = False)
for name, gdf in grouped:
    print(name)

0000
0005
0006
0010
0011
0015
0020
0025
0028
0030
0031
0035
0036
0040
0045
0046
0050
0055
0100
0101
0105
0106
0110
0111
0115
0116
0120
0121
0125
0126
0130
0131
0135
0136
0140
0141
0145
0146
0150
0151
0155
0156
0200
0201
0205
0206
0210
0211
0215
0220
0221
0225
0226
0230
0231
0235
0236
0240
0241
0242
0245
0246
0250
0251
0255
0256
0300
0301
0305
0310
0311
0315
0316
0320
0325
0326
0330
0331
0335
0336
0340
0341
0345
0346
0350
0351
0355
0356
0400
0402
0405
0406
0410
0415
0420
0425
0430
0435
0436
0440
0445
0446
0450
0451
0455
0500
0501
0505
0506
0510
0515
0520
0525
0530
0531
0535
0540
0545
0550
0551
0555
0600
0601
0605
0610
0615
0616
0620
0625
0626
0630
0635
0636
0640
0645
0650
0655
0700
0705
0710
0715
0716
0720
0725
0726
0730
0731
0735
0736
0740
0741
0745
0746
0750
0751
0755
0756
0800
0801
0805
0806
0810
0811
0815
0816
0820
0821
0825
0826
0830
0831
0835
0836
0840
0841
0845
0846
0850
0851
0855
0856
0859
0900
0901
0905
0906
0910
0911
0915
0916
0920
0921
0925
0926
0930
0931
0935
0936
0940
0941
0945
0946
0950
0951
0955
0956
1000
1001
1005
1006
1010
1011
1015
1016
1020
1021
1025
1026
1030
1031
1035
1036
1040
1041
1045
1046
1050
1051
1055
1056
1100
1101
1105
1106
1110
1111
1115
1116
1120
1121
1125
1126
1130
1131
1135
1136
1140
1141
1145
1146
1150
1151
1155
1156
1200
1201
1205
1206
1210
1211
1215
1216
1220
1221
1225
1226
1230
1231
1235
1236
1240
1241
1245
1246
1250
1251
1255
1256
1300
1301
1305
1306
1310
1311
1315
1316
1320
1321
1325
1326
1330
1331
1335
1336
1340
1341
1345
1346
1350
1351
1355
1356
1400
1401
1405
1406
1410
1411
1415
1416
1420
1421
1425
1426
1430
1431
1435
1436
1440
1441
1445
1450
1455
1456
1500
1505
1510
1511
1515
1516
1520
1525
1526
1530
1535
1540
1545
1550
1551
1552
1555
1556
1600
1605
1610
1615
1620
1625
1626
1630
1631
1635
1640
1641
1645
1646
1650
1655
1700
1705
1710
1715
1720
1725
1730
1735
1740
1745
1750
1755
1800
1805
1810
1815
1820
1825
1830
1831
1835
1840
1845
1850
1851
1855
1856
1900
1905
1910
1915
1920
1921
1925
1930
1935
1940
1941
1945
1946
1950
1951
1955
2000
2005
2010
2011
2015
2020
2025
2030
2031
2035
2036
2040
2041
2045
2050
2055
2100
2105
2110
2115
2120
2121
2125
2130
2135
2140
2145
2150
2155
2200
2205
2210
2211
2215
2220
2225
2230
2235
2240
2245
2250
2255
2300
2305
2306
2310
2315
2316
2320
2325
2330
2331
2335
2340
2345
2350
2351
2355
2356
2357

In [25]:
# Select entries that do not fall on a 5-minute interval
df[~df['interval'].str.slice(start=-2).isin(['00','05','10','15','20','25','30','35','40','45','50','55'])]

                     date  vehicles interval
1388  2019-01-06 00:28:00         0     0028
3169  2019-01-12 13:31:00         3     1331
5058  2019-01-12 13:31:00         3     1331
6729  2019-01-25 13:56:00         0     1356
6741  2019-01-25 14:56:00         0     1456
6745  2019-01-25 15:16:00         3     1516
6760  2019-01-25 16:31:00         0     1631
6913  2019-01-26 06:16:00         0     0616
6937  2019-01-26 08:16:00         0     0816
6938  2019-01-26 08:21:00         1     0821
6941  2019-01-26 08:36:00         0     0836
6997  2019-01-26 13:16:00         0     1316
7133  2019-01-27 00:36:00         0     0036
7135  2019-01-27 00:46:00         1     0046
7138  2019-01-27 01:01:00         0     0101
7140  2019-01-27 01:11:00         0     0111
7148  2019-01-27 01:51:00         0     0151
7174  2019-01-27 04:02:00         0     0402
7258  2019-01-27 11:01:00         0     1101
7263  2019-01-27 11:26:00         1     1126
7283  2019-01-27 13:06:00         1     1306
7301  2019-01-27 14:36:00         0     1436
7317  2019-01-27 15:56:00         1     1556
7428  2019-01-28 01:11:00         0     0111
7457  2019-01-28 04:46:00         0     0446
7487  2019-01-28 07:16:00         2     0716
7492  2019-01-28 07:41:00         1     0741
7510  2019-01-28 09:11:00         1     0911
7516  2019-01-28 09:41:00         0     0941
7517  2019-01-28 09:46:00         0     0946
...                   ...       ...      ...
20556 2019-03-18 04:06:00         0     0406
20562 2019-03-18 04:36:00         0     0436
20606 2019-03-18 08:16:00         0     0816
20608 2019-03-18 08:26:00         1     0826
20610 2019-03-18 08:36:00         0     0836
20618 2019-03-18 09:16:00         1     0916
20620 2019-03-18 09:26:00         1     0926
20621 2019-03-18 09:31:00         0     0931
20624 2019-03-18 09:46:00         0     0946
20633 2019-03-18 10:31:00         0     1031
20642 2019-03-18 11:16:00         2     1116
20643 2019-03-18 11:21:00         0     1121
20649 2019-03-18 11:51:00         2     1151
20657 2019-03-18 12:31:00         6     1231
20659 2019-03-18 12:41:00         2     1241
20660 2019-03-18 12:46:00         1     1246
20661 2019-03-18 12:51:00         1     1251
20665 2019-03-18 13:11:00         1     1311
20668 2019-03-18 13:26:00         4     1326
20670 2019-03-18 13:36:00         1     1336
20680 2019-03-18 14:26:00         5     1426
20689 2019-03-18 15:11:00         0     1511
20805 2019-03-19 01:16:00         0     0116
21640 2019-03-21 23:56:00         0     2356
21770 2019-03-22 11:16:00         0     1116
21932 2019-03-23 01:11:00         0     0111
22340 2019-03-24 11:46:00         0     1146
22341 2019-03-24 11:51:00         4     1151
22342 2019-03-24 11:56:00         2     1156
22343 2019-03-24 12:01:00         1     1201

[450 rows x 3 columns]